### ISSUE TITLE
Cela ne marche pas.

### ISSUE THREAD

**Issue by venaxyt** [Its-Vichy/Batched-Grabber#1]
Bonjour Vichy, le concept m'a paru génial vu que les seuls token grabbers en Batch ne fonctionnent plus depuis bien longtemps maintenant, donc j'ai essayé ton script, il s'est bien compilé, j'ai bien mis le nom et le webhook, le grabber s'est bien obfusqué vu qu'il fait 69ko et que j'ai vu dedans, seul problème, je ne pense pas avoir fait d'erreur et il ne marche pas. Je te met une capture d'écran de l'erreur : La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte.
![image](https://user-images.githubusercontent.com/81310818/131640455-a7d16ece-23b2-4512-b10d-b4daa64366a4.png)
Cordialement, Venax.

**Comment by Its-Vichy** [comment]
Bonsoir,
Le token grabber est bien fonctionel.
Cette erreur proviens du `cd %temmp%` (L'obfuscation fais de la merde avec le %).
Elle n'est cependante aucunement la cause du bug (Car de mon côté aucun soucis avec ça)

Laissez simplement le grabber et au bout de ~10s tous seras envoyer via discord.

**Comment by venaxyt** [comment]
Bonsoir aussi,
En fait des le début le programme se ferme me retournant cette erreur, donc faudrait il que je cherche à encrypter le fichier différemment ?
Car cela ne fonctionne donc pas pour moi,
Merci, cordialement, Venax.

**Comment by Its-Vichy** [comment]
Dans ce cas, retirez le `cd %temp%` dans **./Files/batch.txt**, et regardez ce que ça donne.

**Comment by venaxyt** [comment]
Cela ne m'affiche plus d'erreur, mais cela n'envoie rien et se ferme au bout de moins d'une seconde.

**Comment by Its-Vichy** [comment]
Un fichier powershell est-il générer ?

**Comment by venaxyt** [comment]
Non, aucun, uniquement un fichier batch.

**Comment by venaxyt** [comment]
Dans tous les car ne t'inquiètes pas cela ne fait rien je suis déjà sur d'autres projets je trouvait juste ça rigolo d'essayer ce nouveau script, merci pour ton temps dans tous les cas, bonne soirée et rentrée !

**Comment by Its-Vichy** [comment]
Pas de soucis, de même.

**Comment by venaxyt** [comment]
Hey, j'aide quand je peux, j'ai trouvé comment solutionner ce problème par hasard alors que j'étais en train de debloat mon Windows, tout simplement mon pc ne pouvais pas lancer de .ps1 car le powershell l'empêchait pour des raisons de sécurité, il faut donc aller dans le powershell en admin et faire : set-executionpolicy unrestricted

**Comment by Its-Vichy** [comment]
Bien vue, je met à jour !
