### ISSUE TITLE
Colorfull Doesnt exist anymore

### ISSUE THREAD

**Issue by PandoricGalaxy** [Its-Vichy/Batched-Grabber#2]
![image](https://user-images.githubusercontent.com/86944806/161587387-1e46f73b-cd74-4377-8221-0d70f99cbe8a.png)
tried searching and found that their Pypi and github was removed???
colorfull doest exist now!

**Comment by PandoricGalaxy** [comment]
Why closed it what happened?

**Comment by lucxws** [comment]
Bait, check his github repo related to discord
